services:
     - type: web
       name: talk2hire-frontend
       env: static
       rootDir: frontend
       buildCommand: npm install && npm run build
       staticPublishPath: ./dist
       routes:
         - type: rewrite
           source: /:path*
           destination: /index.html
